// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExpressionFramework.Core.DomainModel.Builders
{
#nullable enable
    public partial class ConditionBuilder : ExpressionFramework.Abstractions.DomainModel.Builders.IConditionBuilder
    {
        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder LeftExpression
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.Domains.Operator Operator
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder RightExpression
        {
            get;
            set;
        }

        public bool StartGroup
        {
            get;
            set;
        }

        public bool EndGroup
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.Domains.Combination Combination
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.ICondition Build()
        {
            return new ExpressionFramework.Core.DomainModel.Condition(LeftExpression.Build(), Operator, RightExpression.Build(), StartGroup, EndGroup, Combination);
        }

        public ConditionBuilder()
        {
            LeftExpression = new ExpressionFramework.Core.DomainModel.Builders.EmptyExpressionBuilder();
            Operator = default;
            RightExpression = new ExpressionFramework.Core.DomainModel.Builders.EmptyExpressionBuilder();
            StartGroup = default;
            EndGroup = default;
            Combination = default;
        }

        public ConditionBuilder(ExpressionFramework.Abstractions.DomainModel.ICondition source)
        {
            LeftExpression = source.LeftExpression.ToBuilder();
            Operator = source.Operator;
            RightExpression = source.RightExpression.ToBuilder();
            StartGroup = source.StartGroup;
            EndGroup = source.EndGroup;
            Combination = source.Combination;
        }
    }
#nullable restore

#nullable enable
    public partial class ConstantExpressionBuilder : ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder
    {
        public object? Value
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? Function
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.IExpression Build()
        {
            return new ExpressionFramework.Core.DomainModel.ConstantExpression(Value, Function?.Build());
        }

        public ConstantExpressionBuilder()
        {
        }

        public ConstantExpressionBuilder(ExpressionFramework.Abstractions.DomainModel.IConstantExpression source)
        {
            Value = source.Value;
            Function = source.Function == null ? null : source.Function.ToBuilder();
        }
    }
#nullable restore

#nullable enable
    public partial class DelegateExpressionBuilder : ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder
    {
        public System.Func<object?,ExpressionFramework.Abstractions.DomainModel.IExpression,ExpressionFramework.Abstractions.IExpressionEvaluator,object?> ValueDelegate
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? Function
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.IExpression Build()
        {
            return new ExpressionFramework.Core.DomainModel.DelegateExpression(ValueDelegate, Function?.Build());
        }

        public DelegateExpressionBuilder()
        {
            ValueDelegate = new Func<object?, IExpression, IExpressionEvaluator, object?>((_, _, _) => null);
        }

        public DelegateExpressionBuilder(ExpressionFramework.Abstractions.DomainModel.IDelegateExpression source)
        {
            ValueDelegate = source.ValueDelegate;
            Function = source.Function == null ? null : source.Function.ToBuilder();
        }
    }
#nullable restore

#nullable enable
    public partial class EmptyExpressionBuilder : ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder
    {
        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? Function
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.IExpression Build()
        {
            return new ExpressionFramework.Core.DomainModel.EmptyExpression(Function?.Build());
        }

        public EmptyExpressionBuilder()
        {
        }

        public EmptyExpressionBuilder(ExpressionFramework.Abstractions.DomainModel.IEmptyExpression source)
        {
            Function = source.Function == null ? null : source.Function.ToBuilder();
        }
    }
#nullable restore

#nullable enable
    public partial class FieldExpressionBuilder : ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder
    {
        public string FieldName
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? Function
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.IExpression Build()
        {
            return new ExpressionFramework.Core.DomainModel.FieldExpression(FieldName, Function?.Build());
        }

        public FieldExpressionBuilder()
        {
            FieldName = string.Empty;
        }

        public FieldExpressionBuilder(ExpressionFramework.Abstractions.DomainModel.IFieldExpression source)
        {
            FieldName = source.FieldName;
            Function = source.Function == null ? null : source.Function.ToBuilder();
        }
    }
#nullable restore
}
