// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExpressionFramework.Core.DomainModel.Builders
{
#nullable enable
    public partial class ConditionBuilder : ExpressionFramework.Abstractions.DomainModel.Builders.IConditionBuilder
    {
        public bool OpenBracket
        {
            get;
            set;
        }

        public bool CloseBracket
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder LeftExpression
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.Domains.Operator Operator
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder RightExpression
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.Domains.Combination Combination
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.ICondition Build()
        {
            return new ExpressionFramework.Core.DomainModel.Condition(OpenBracket, CloseBracket, LeftExpression.Build(), Operator, RightExpression.Build(), Combination);
        }

        public ConditionBuilder()
        {
            OpenBracket = default;
            CloseBracket = default;
            LeftExpression = new ExpressionFramework.Core.DomainModel.Builders.ExpressionBuilder();
            Operator = default;
            RightExpression = new ExpressionFramework.Core.DomainModel.Builders.ExpressionBuilder();
            Combination = default;
        }

        public ConditionBuilder(ExpressionFramework.Abstractions.DomainModel.ICondition source)
        {
            OpenBracket = source.OpenBracket;
            CloseBracket = source.CloseBracket;
            LeftExpression = new ExpressionFramework.Core.DomainModel.Builders.ExpressionBuilder(source.LeftExpression);
            Operator = source.Operator;
            RightExpression = new ExpressionFramework.Core.DomainModel.Builders.ExpressionBuilder(source.RightExpression);
            Combination = source.Combination;
        }
    }
#nullable restore

#nullable enable
    public partial class ExpressionBuilder : ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder
    {
        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? Function
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.IExpression Build()
        {
            return new ExpressionFramework.Core.DomainModel.Expression(Function?.Build());
        }

        public ExpressionBuilder()
        {
        }

        public ExpressionBuilder(ExpressionFramework.Abstractions.DomainModel.IExpression source)
        {
            Function = source.Function == null ? null : source.Function.ToBuilder();
        }
    }
#nullable restore

#nullable enable
    public partial class FieldExpressionBuilder : ExpressionFramework.Abstractions.DomainModel.Builders.IFieldExpressionBuilder
    {
        public string FieldName
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? Function
        {
            get;
            set;
        }

        public ExpressionFramework.Abstractions.DomainModel.IFieldExpression Build()
        {
            return new ExpressionFramework.Core.DomainModel.FieldExpression(FieldName, Function?.Build());
        }

        public FieldExpressionBuilder()
        {
            FieldName = string.Empty;
        }

        public FieldExpressionBuilder(ExpressionFramework.Abstractions.DomainModel.IFieldExpression source)
        {
            FieldName = source.FieldName;
            Function = source.Function == null ? null : source.Function.ToBuilder();
        }
    }
#nullable restore
}
