// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExpressionFramework.Core.DomainModel
{
#nullable enable
    public partial record Condition : ExpressionFramework.Abstractions.DomainModel.ICondition
    {
        public bool OpenBracket
        {
            get;
        }

        public bool CloseBracket
        {
            get;
        }

        public ExpressionFramework.Abstractions.DomainModel.IExpression LeftExpression
        {
            get;
        }

        public ExpressionFramework.Abstractions.DomainModel.Domains.Operator Operator
        {
            get;
        }

        public ExpressionFramework.Abstractions.DomainModel.IExpression RightExpression
        {
            get;
        }

        public ExpressionFramework.Abstractions.DomainModel.Domains.Combination Combination
        {
            get;
        }

        public Condition(bool openBracket, bool closeBracket, ExpressionFramework.Abstractions.DomainModel.IExpression leftExpression, ExpressionFramework.Abstractions.DomainModel.Domains.Operator @operator, ExpressionFramework.Abstractions.DomainModel.IExpression rightExpression, ExpressionFramework.Abstractions.DomainModel.Domains.Combination combination)
        {
            this.OpenBracket = openBracket;
            this.CloseBracket = closeBracket;
            this.LeftExpression = leftExpression;
            this.Operator = @operator;
            this.RightExpression = rightExpression;
            this.Combination = combination;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore

#nullable enable
    public partial record Expression : ExpressionFramework.Abstractions.DomainModel.IExpression
    {
        public string FieldName
        {
            get;
        }

        public ExpressionFramework.Abstractions.DomainModel.IExpressionFunction? Function
        {
            get;
        }

        public Expression(string fieldName, ExpressionFramework.Abstractions.DomainModel.IExpressionFunction? function)
        {
            this.FieldName = fieldName;
            this.Function = function;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}
