// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExpressionFramework.Abstractions.DomainModel.Extensions
{
#nullable enable
    public static partial class ConditionBuilderExtensions
    {
        public static T WithLeftExpression<T>(this T instance, ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder leftExpression)
            where T : ExpressionFramework.Abstractions.DomainModel.Builders.IConditionBuilder
        {
            instance.LeftExpression = leftExpression;
            return instance;
        }

        public static T WithOperator<T>(this T instance, ExpressionFramework.Abstractions.DomainModel.Domains.Operator @operator)
            where T : ExpressionFramework.Abstractions.DomainModel.Builders.IConditionBuilder
        {
            instance.Operator = @operator;
            return instance;
        }

        public static T WithRightExpression<T>(this T instance, ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder rightExpression)
            where T : ExpressionFramework.Abstractions.DomainModel.Builders.IConditionBuilder
        {
            instance.RightExpression = rightExpression;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class ConstantExpressionBuilderExtensions
    {
        public static T WithValue<T>(this T instance, object? value)
            where T : ExpressionFramework.Abstractions.DomainModel.Builders.IConstantExpressionBuilder
        {
            instance.Value = value;
            return instance;
        }

        public static T WithFunction<T>(this T instance, ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? function)
            where T : ExpressionFramework.Abstractions.DomainModel.Builders.IConstantExpressionBuilder
        {
            instance.Function = function;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class EmptyExpressionBuilderExtensions
    {
        public static T WithFunction<T>(this T instance, ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? function)
            where T : ExpressionFramework.Abstractions.DomainModel.Builders.IEmptyExpressionBuilder
        {
            instance.Function = function;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class ExpressionBuilderExtensions
    {
        public static T WithFunction<T>(this T instance, ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? function)
            where T : ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder
        {
            instance.Function = function;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class ExpressionFunctionBuilderExtensions
    {
        public static T WithInnerFunction<T>(this T instance, ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? innerFunction)
            where T : ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder
        {
            instance.InnerFunction = innerFunction;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class FieldExpressionBuilderExtensions
    {
        public static T WithFieldName<T>(this T instance, string fieldName)
            where T : ExpressionFramework.Abstractions.DomainModel.Builders.IFieldExpressionBuilder
        {
            instance.FieldName = fieldName;
            return instance;
        }

        public static T WithFunction<T>(this T instance, ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? function)
            where T : ExpressionFramework.Abstractions.DomainModel.Builders.IFieldExpressionBuilder
        {
            instance.Function = function;
            return instance;
        }
    }
#nullable restore
}
