// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ExpressionFramework.Abstractions.DomainModel.Builders
{
#nullable enable
    public partial interface IConditionBuilder
    {
        ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder LeftExpression
        {
            get;
            set;
        }

        ExpressionFramework.Abstractions.DomainModel.Domains.Operator Operator
        {
            get;
            set;
        }

        ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder RightExpression
        {
            get;
            set;
        }

        bool StartGroup
        {
            get;
            set;
        }

        bool EndGroup
        {
            get;
            set;
        }

        ExpressionFramework.Abstractions.DomainModel.Domains.Combination Combination
        {
            get;
            set;
        }

        ExpressionFramework.Abstractions.DomainModel.ICondition Build();
    }
#nullable restore

#nullable enable
    public partial interface IExpressionBuilder
    {
        ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? Function
        {
            get;
            set;
        }

        ExpressionFramework.Abstractions.DomainModel.IExpression Build();
    }
#nullable restore

#nullable enable
    public partial interface IExpressionFunctionBuilder
    {
        ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionFunctionBuilder? InnerFunction
        {
            get;
            set;
        }

        ExpressionFramework.Abstractions.DomainModel.IExpressionFunction Build();
    }
#nullable restore
}
