// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.6
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace QueryFramework.Abstractions.Builders
{
    public partial interface IConditionBuilder
    {
        System.StringComparison StringComparison
        {
            get;
            set;
        }

        CrossCutting.Utilities.ExpressionEvaluator.IEvaluatable LeftExpression
        {
            get;
            set;
        }

        QueryFramework.Abstractions.Builders.IOperatorBuilder Operator
        {
            get;
            set;
        }

        CrossCutting.Utilities.ExpressionEvaluator.IEvaluatable RightExpression
        {
            get;
            set;
        }

        System.Nullable<QueryFramework.Abstractions.Domains.Combination> Combination
        {
            get;
            set;
        }

        bool StartGroup
        {
            get;
            set;
        }

        bool EndGroup
        {
            get;
            set;
        }

        QueryFramework.Abstractions.ICondition Build();
    }
    public partial interface IDataObjectNameQueryBuilder : QueryFramework.Abstractions.Builders.IQueryBuilder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        string DataObjectName
        {
            get;
            set;
        }

        new QueryFramework.Abstractions.IDataObjectNameQuery Build();
    }
    public partial interface IFieldSelectionQueryBuilder : QueryFramework.Abstractions.Builders.IQueryBuilder
    {
        bool Distinct
        {
            get;
            set;
        }

        bool GetAllFields
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        System.Collections.Generic.List<string> FieldNames
        {
            get;
            set;
        }

        new QueryFramework.Abstractions.IFieldSelectionQuery Build();
    }
    public partial interface IGroupingQueryBuilder : QueryFramework.Abstractions.Builders.IQueryBuilder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        System.Collections.Generic.List<CrossCutting.Utilities.ExpressionEvaluator.IExpression> GroupByFields
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        [QueryFramework.Abstractions.Validation.ValidGroupsAttribute]
        System.Collections.Generic.List<QueryFramework.Abstractions.Builders.IConditionBuilder> GroupByFilter
        {
            get;
            set;
        }

        new QueryFramework.Abstractions.IGroupingQuery Build();
    }
    public partial interface IOperatorBuilder
    {
        QueryFramework.Abstractions.IOperator Build();
    }
    public partial interface IParameterizedQueryBuilder : QueryFramework.Abstractions.Builders.IQueryBuilder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        System.Collections.Generic.List<QueryFramework.Abstractions.Builders.IQueryParameterBuilder> Parameters
        {
            get;
            set;
        }

        new QueryFramework.Abstractions.IParameterizedQuery Build();
    }
    public partial interface IQueryBuilder
    {
        System.Nullable<int> Limit
        {
            get;
            set;
        }

        System.Nullable<int> Offset
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        [QueryFramework.Abstractions.Validation.ValidGroupsAttribute]
        System.Collections.Generic.List<QueryFramework.Abstractions.Builders.IConditionBuilder> Filter
        {
            get;
            set;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        System.Collections.Generic.List<QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder> OrderByFields
        {
            get;
            set;
        }

        QueryFramework.Abstractions.IQuery Build();
    }
    public partial interface IQueryParameterBuilder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        string Name
        {
            get;
            set;
        }

        object? Value
        {
            get;
            set;
        }

        QueryFramework.Abstractions.IQueryParameter Build();
    }
    public partial interface IQueryParameterValueBuilder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        string Name
        {
            get;
            set;
        }

        QueryFramework.Abstractions.IQueryParameterValue Build();
    }
    public partial interface IQuerySortOrderBuilder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        CrossCutting.Utilities.ExpressionEvaluator.IExpression<string> FieldNameExpression
        {
            get;
            set;
        }

        QueryFramework.Abstractions.Domains.QuerySortOrderDirection Order
        {
            get;
            set;
        }

        QueryFramework.Abstractions.IQuerySortOrder Build();
    }
    public partial interface ISingleEntityQueryBuilder : QueryFramework.Abstractions.Builders.IQueryBuilder
    {
        new QueryFramework.Abstractions.ISingleEntityQuery Build();
    }
}
#nullable disable
