// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QueryFramework.Abstractions.Builders
{
#nullable enable
    public partial interface IQueryParameterBuilder
    {
        string Name
        {
            get;
            set;
        }

        object Value
        {
            get;
            set;
        }

        QueryFramework.Abstractions.IQueryParameter Build();
    }
#nullable restore

#nullable enable
    public partial interface IQueryParameterValueBuilder
    {
        string Name
        {
            get;
            set;
        }

        QueryFramework.Abstractions.IQueryParameterValue Build();
    }
#nullable restore

#nullable enable
    public partial interface IQuerySortOrderBuilder
    {
        ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder Field
        {
            get;
            set;
        }

        QueryFramework.Abstractions.QuerySortOrderDirection Order
        {
            get;
            set;
        }

        QueryFramework.Abstractions.IQuerySortOrder Build();
    }
#nullable restore
}
