// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.6
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace QueryFramework.Core.Builders
{
    public abstract partial class ConditionBuilder<TBuilder, TEntity> : ConditionBuilder, QueryFramework.Abstractions.Builders.IConditionBuilder
        where TEntity : QueryFramework.Core.Condition
        where TBuilder : ConditionBuilder<TBuilder, TEntity>
    {
        protected ConditionBuilder(QueryFramework.Abstractions.ICondition source) : base(source)
        {
        }

        protected ConditionBuilder() : base()
        {
        }

        public override QueryFramework.Core.Condition Build()
        {
            return BuildTyped();
        }

        public abstract TEntity BuildTyped();

        QueryFramework.Abstractions.ICondition QueryFramework.Abstractions.Builders.IConditionBuilder.Build()
        {
            return BuildTyped();
        }

        public static implicit operator QueryFramework.Core.Condition(ConditionBuilder<TBuilder, TEntity> entity)
        {
            return entity.BuildTyped();
        }
    }
    public abstract partial class QueryBuilder<TBuilder, TEntity> : QueryBuilder, QueryFramework.Abstractions.Builders.IQueryBuilder
        where TEntity : QueryFramework.Core.Query
        where TBuilder : QueryBuilder<TBuilder, TEntity>
    {
        protected QueryBuilder(QueryFramework.Abstractions.IQuery source) : base(source)
        {
        }

        protected QueryBuilder() : base()
        {
        }

        public override QueryFramework.Core.Query Build()
        {
            return BuildTyped();
        }

        public abstract TEntity BuildTyped();

        QueryFramework.Abstractions.IQuery QueryFramework.Abstractions.Builders.IQueryBuilder.Build()
        {
            return BuildTyped();
        }

        public static implicit operator QueryFramework.Core.Query(QueryBuilder<TBuilder, TEntity> entity)
        {
            return entity.BuildTyped();
        }
    }
}
#nullable disable
