// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 8.0.10
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace QueryFramework.Core.Builders
{
    public abstract partial class QueryBuilder : QueryFramework.Abstractions.Builders.IQueryBuilder, System.ComponentModel.INotifyPropertyChanged
    {
        private System.Nullable<int> _limit;

        private System.Nullable<int> _offset;

        private ExpressionFramework.Domain.Builders.Evaluatables.ComposedEvaluatableBuilder _filter;

        private System.Collections.Generic.List<QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder> _orderByFields;

        public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;

        public System.Nullable<int> Limit
        {
            get
            {
                return _limit;
            }
            set
            {
                _limit = value;
                HandlePropertyChanged(nameof(Limit));
            }
        }

        public System.Nullable<int> Offset
        {
            get
            {
                return _offset;
            }
            set
            {
                _offset = value;
                HandlePropertyChanged(nameof(Offset));
            }
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public ExpressionFramework.Domain.Builders.Evaluatables.ComposedEvaluatableBuilder Filter
        {
            get
            {
                return _filter;
            }
            set
            {
                _filter = value;
                HandlePropertyChanged(nameof(Filter));
            }
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public System.Collections.Generic.List<QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder> OrderByFields
        {
            get
            {
                return _orderByFields;
            }
            set
            {
                _orderByFields = value;
                HandlePropertyChanged(nameof(OrderByFields));
            }
        }

        protected QueryBuilder(QueryFramework.Abstractions.IQuery source)
        {
            _orderByFields = new System.Collections.Generic.List<QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder>();
            _limit = source.Limit;
            _offset = source.Offset;
            _filter = new ExpressionFramework.Domain.Builders.Evaluatables.ComposedEvaluatableBuilder(source.Filter);
            foreach (var item in source.OrderByFields.Select(x => x.ToBuilder())) _orderByFields.Add(item);
        }

        protected QueryBuilder()
        {
            _orderByFields = new System.Collections.Generic.List<QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder>();
            _filter = new ExpressionFramework.Domain.Builders.Evaluatables.ComposedEvaluatableBuilder()!;
            SetDefaultValues();
        }

        public abstract QueryFramework.Abstractions.IQuery Build();

        partial void SetDefaultValues();

        protected void HandlePropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
        }
    }
}
#nullable disable
