// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QueryFramework.Core.Builders
{
#nullable enable
    public partial class QueryParameterBuilder : QueryFramework.Abstractions.Builders.IQueryParameterBuilder
    {
        public string Name
        {
            get;
            set;
        }

        public object Value
        {
            get;
            set;
        }

        public QueryFramework.Abstractions.IQueryParameter Build()
        {
            return new QueryFramework.Core.QueryParameter(Name, Value);
        }

        public QueryParameterBuilder()
        {
            Name = string.Empty;
            Value = new object();
        }

        public QueryParameterBuilder(QueryFramework.Abstractions.IQueryParameter source)
        {
            Name = source.Name;
            Value = source.Value;
        }
    }
#nullable restore

#nullable enable
    public partial class QueryParameterValueBuilder : QueryFramework.Abstractions.Builders.IQueryParameterValueBuilder
    {
        public string Name
        {
            get;
            set;
        }

        public QueryFramework.Abstractions.IQueryParameterValue Build()
        {
            return new QueryFramework.Core.QueryParameterValue(Name);
        }

        public QueryParameterValueBuilder()
        {
            Name = string.Empty;
        }

        public QueryParameterValueBuilder(QueryFramework.Abstractions.IQueryParameterValue source)
        {
            Name = source.Name;
        }
    }
#nullable restore

#nullable enable
    public partial class QuerySortOrderBuilder : QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder
    {
        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder Field
        {
            get;
            set;
        }

        public QueryFramework.Abstractions.QuerySortOrderDirection Order
        {
            get;
            set;
        }

        public QueryFramework.Abstractions.IQuerySortOrder Build()
        {
            return new QueryFramework.Core.QuerySortOrder(Field.Build(), Order);
        }

        public QuerySortOrderBuilder()
        {
            Field = new ExpressionFramework.Core.DomainModel.Builders.EmptyExpressionBuilder();
            Order = default;
        }

        public QuerySortOrderBuilder(QueryFramework.Abstractions.IQuerySortOrder source)
        {
            Field = source.Field.ToBuilder();
            Order = source.Order;
        }
    }
#nullable restore
}
