// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.3
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QueryFramework.Core.Builders
{
#nullable enable
    public partial class QuerySortOrderBuilder : QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder
    {
        public ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder Field
        {
            get;
            set;
        }

        public QueryFramework.Abstractions.QuerySortOrderDirection Order
        {
            get;
            set;
        }

        public QueryFramework.Abstractions.IQuerySortOrder Build()
        {
            return new QueryFramework.Core.QuerySortOrder(Field.Build(), Order);
        }

        public QuerySortOrderBuilder()
        {
            Field = new ExpressionFramework.Core.DomainModel.Builders.EmptyExpressionBuilder();
            Order = default;
        }

        public QuerySortOrderBuilder(QueryFramework.Abstractions.IQuerySortOrder source)
        {
            Field = source.Field.ToBuilder();
            Order = source.Order;
        }
    }
#nullable restore
}

