global using System.Linq;
global using ExpressionFramework.Abstractions.DomainModel.Domains;
global using ExpressionFramework.Core.DomainModel.Builders;
global using FluentAssertions;
global using QueryFramework.Abstractions;
global using QueryFramework.Abstractions.Queries.Builders;
global using QueryFramework.Core.Queries.Builders;
global using QueryFramework.QueryParsers.Extensions;
global using Xunit;
