global using System;
global using System.Linq;
global using ExpressionFramework.Domain.Builders.Expressions;
global using ExpressionFramework.Domain.Builders.Operators;
global using FluentAssertions;
global using QueryFramework.Abstractions.Builders.Queries;
global using QueryFramework.Abstractions.Extensions;
global using QueryFramework.Core.Builders.Queries;
global using Xunit;
