global using System.Linq;
global using FluentAssertions;
global using QueryFramework.Abstractions;
global using QueryFramework.Abstractions.Extensions;
global using QueryFramework.Abstractions.Queries.Builders;
global using QueryFramework.Core.Builders;
global using QueryFramework.Core.Queries.Builders;
global using QueryFramework.QueryParsers.Extensions;
global using Xunit;
