// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.6
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace QueryFramework.Core
{
    public abstract partial record Condition : QueryFramework.Abstractions.ICondition
    {
        protected Condition()
        {
        }

        public abstract QueryFramework.Abstractions.Builders.IConditionBuilder ToBuilder();

        QueryFramework.Abstractions.Builders.IConditionBuilder QueryFramework.Abstractions.ICondition.ToBuilder()
        {
            return ToBuilder();
        }
    }
    public abstract partial record Query : QueryFramework.Abstractions.IQuery
    {
        public System.Nullable<int> Limit
        {
            get;
        }

        public System.Nullable<int> Offset
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        [QueryFramework.Abstractions.Validation.ValidGroupsAttribute]
        public System.Collections.Generic.IReadOnlyCollection<QueryFramework.Abstractions.ICondition> Filter
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        public System.Collections.Generic.IReadOnlyCollection<QueryFramework.Abstractions.IQuerySortOrder> OrderByFields
        {
            get;
        }

        protected Query(System.Nullable<int> limit, System.Nullable<int> offset, System.Collections.Generic.IEnumerable<QueryFramework.Abstractions.ICondition> filter, System.Collections.Generic.IEnumerable<QueryFramework.Abstractions.IQuerySortOrder> orderByFields)
        {
            if (filter is null) throw new System.ArgumentNullException(nameof(filter));
            if (orderByFields is null) throw new System.ArgumentNullException(nameof(orderByFields));
            this.Limit = limit;
            this.Offset = offset;
            this.Filter = new CrossCutting.Common.ReadOnlyValueCollection<QueryFramework.Abstractions.ICondition>(filter);
            this.OrderByFields = new CrossCutting.Common.ReadOnlyValueCollection<QueryFramework.Abstractions.IQuerySortOrder>(orderByFields);
        }

        public abstract QueryFramework.Abstractions.Builders.IQueryBuilder ToBuilder();

        QueryFramework.Abstractions.Builders.IQueryBuilder QueryFramework.Abstractions.IQuery.ToBuilder()
        {
            return ToBuilder();
        }
    }
}
#nullable disable
