// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QueryFramework.Core
{
#nullable enable
    public partial record QuerySortOrder : QueryFramework.Abstractions.IQuerySortOrder
    {
        public ExpressionFramework.Abstractions.DomainModel.IExpression Field
        {
            get;
        }

        public QueryFramework.Abstractions.QuerySortOrderDirection Order
        {
            get;
        }

        public QuerySortOrder(ExpressionFramework.Abstractions.DomainModel.IExpression field, QueryFramework.Abstractions.QuerySortOrderDirection order)
        {
            this.Field = field;
            this.Order = order;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }
    }
#nullable restore
}

