// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.6
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace QueryFramework.Core.Builders.Conditions
{
    public partial class ComposableConditionBuilder : QueryFramework.Core.Builders.ConditionBuilder<ComposableConditionBuilder, QueryFramework.Core.Conditions.ComposableCondition>, QueryFramework.Abstractions.Builders.IConditionBuilder
    {
        private System.StringComparison _stringComparison;

        private QueryFramework.Abstractions.Builders.IExpressionBuilder _leftExpression;

        private QueryFramework.Abstractions.Builders.IOperatorBuilder _operator;

        private QueryFramework.Abstractions.Builders.IExpressionBuilder _rightExpression;

        private System.Nullable<QueryFramework.Abstractions.Domains.Combination> _combination;

        private bool _startGroup;

        private bool _endGroup;

        public System.StringComparison StringComparison
        {
            get
            {
                return _stringComparison;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.StringComparison>.Default.Equals(_stringComparison, value);
                _stringComparison = value;
                if (hasChanged) HandlePropertyChanged(nameof(StringComparison));
            }
        }

        public QueryFramework.Abstractions.Builders.IExpressionBuilder LeftExpression
        {
            get
            {
                return _leftExpression;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<QueryFramework.Abstractions.Builders.IExpressionBuilder>.Default.Equals(_leftExpression!, value!);
                _leftExpression = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(LeftExpression));
            }
        }

        public QueryFramework.Abstractions.Builders.IOperatorBuilder Operator
        {
            get
            {
                return _operator;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<QueryFramework.Abstractions.Builders.IOperatorBuilder>.Default.Equals(_operator!, value!);
                _operator = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(Operator));
            }
        }

        public QueryFramework.Abstractions.Builders.IExpressionBuilder RightExpression
        {
            get
            {
                return _rightExpression;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<QueryFramework.Abstractions.Builders.IExpressionBuilder>.Default.Equals(_rightExpression!, value!);
                _rightExpression = value ?? throw new System.ArgumentNullException(nameof(value));
                if (hasChanged) HandlePropertyChanged(nameof(RightExpression));
            }
        }

        public System.Nullable<QueryFramework.Abstractions.Domains.Combination> Combination
        {
            get
            {
                return _combination;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Nullable<QueryFramework.Abstractions.Domains.Combination>>.Default.Equals(_combination, value);
                _combination = value;
                if (hasChanged) HandlePropertyChanged(nameof(Combination));
            }
        }

        public bool StartGroup
        {
            get
            {
                return _startGroup;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Boolean>.Default.Equals(_startGroup, value);
                _startGroup = value;
                if (hasChanged) HandlePropertyChanged(nameof(StartGroup));
            }
        }

        public bool EndGroup
        {
            get
            {
                return _endGroup;
            }
            set
            {
                bool hasChanged = !System.Collections.Generic.EqualityComparer<System.Boolean>.Default.Equals(_endGroup, value);
                _endGroup = value;
                if (hasChanged) HandlePropertyChanged(nameof(EndGroup));
            }
        }

        public ComposableConditionBuilder(QueryFramework.Abstractions.IComposableCondition source) : base(source)
        {
            if (source is null) throw new System.ArgumentNullException(nameof(source));
            _stringComparison = source.StringComparison;
            _leftExpression = source.LeftExpression?.ToBuilder()!;
            _operator = source.Operator?.ToBuilder()!;
            _rightExpression = source.RightExpression?.ToBuilder()!;
            _combination = source.Combination;
            _startGroup = source.StartGroup;
            _endGroup = source.EndGroup;
        }

        public ComposableConditionBuilder() : base()
        {
            _leftExpression = default(QueryFramework.Abstractions.IExpression)!;
            _operator = default(QueryFramework.Abstractions.IOperator)!;
            _rightExpression = default(QueryFramework.Abstractions.IExpression)!;
            SetDefaultValues();
        }

        public override QueryFramework.Core.Conditions.ComposableCondition BuildTyped()
        {
            return new QueryFramework.Core.Conditions.ComposableCondition(StringComparison, LeftExpression?.Build()!, Operator?.Build()!, RightExpression?.Build()!, Combination, StartGroup, EndGroup);
        }

        QueryFramework.Abstractions.ICondition QueryFramework.Abstractions.Builders.IConditionBuilder.Build()
        {
            return BuildTyped();
        }

        partial void SetDefaultValues();

        public QueryFramework.Core.Builders.Conditions.ComposableConditionBuilder WithStringComparison(System.StringComparison stringComparison)
        {
            StringComparison = stringComparison;
            return this;
        }

        public QueryFramework.Core.Builders.Conditions.ComposableConditionBuilder WithLeftExpression(QueryFramework.Abstractions.Builders.IExpressionBuilder leftExpression)
        {
            if (leftExpression is null) throw new System.ArgumentNullException(nameof(leftExpression));
            LeftExpression = leftExpression;
            return this;
        }

        public QueryFramework.Core.Builders.Conditions.ComposableConditionBuilder WithOperator(QueryFramework.Abstractions.Builders.IOperatorBuilder @operator)
        {
            if (@operator is null) throw new System.ArgumentNullException(nameof(@operator));
            Operator = @operator;
            return this;
        }

        public QueryFramework.Core.Builders.Conditions.ComposableConditionBuilder WithRightExpression(QueryFramework.Abstractions.Builders.IExpressionBuilder rightExpression)
        {
            if (rightExpression is null) throw new System.ArgumentNullException(nameof(rightExpression));
            RightExpression = rightExpression;
            return this;
        }

        public QueryFramework.Core.Builders.Conditions.ComposableConditionBuilder WithCombination(System.Nullable<QueryFramework.Abstractions.Domains.Combination> combination)
        {
            Combination = combination;
            return this;
        }

        public QueryFramework.Core.Builders.Conditions.ComposableConditionBuilder WithStartGroup(bool startGroup = true)
        {
            StartGroup = startGroup;
            return this;
        }

        public QueryFramework.Core.Builders.Conditions.ComposableConditionBuilder WithEndGroup(bool endGroup = true)
        {
            EndGroup = endGroup;
            return this;
        }

        public static implicit operator QueryFramework.Core.Conditions.ComposableCondition(ComposableConditionBuilder entity)
        {
            return entity.BuildTyped();
        }
    }
}
#nullable disable
