// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QueryFramework.Abstractions.Extensions
{
#nullable enable
    public static partial class QueryParameterBuilderExtensions
    {
        public static T WithName<T>(this T instance, string name)
            where T : QueryFramework.Abstractions.Builders.IQueryParameterBuilder
        {
            instance.Name = name;
            return instance;
        }

        public static T WithValue<T>(this T instance, object value)
            where T : QueryFramework.Abstractions.Builders.IQueryParameterBuilder
        {
            instance.Value = value;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class QueryParameterValueBuilderExtensions
    {
        public static T WithName<T>(this T instance, string name)
            where T : QueryFramework.Abstractions.Builders.IQueryParameterValueBuilder
        {
            instance.Name = name;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class QuerySortOrderBuilderExtensions
    {
        public static T WithField<T>(this T instance, ExpressionFramework.Abstractions.DomainModel.Builders.IExpressionBuilder field)
            where T : QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder
        {
            instance.Field = field;
            return instance;
        }

        public static T WithOrder<T>(this T instance, QueryFramework.Abstractions.QuerySortOrderDirection order)
            where T : QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder
        {
            instance.Order = order;
            return instance;
        }

        public static T WithField<T>(this T instance, string fieldName)
            where T : QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder
        {
            instance.Field = new FieldExpressionBuilder().WithFieldName(fieldName);
            return instance;
        }
    }
#nullable restore
}
