// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 5.0.13
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QueryFramework.Abstractions.Extensions
{
#nullable enable
    public static partial class QueryConditionBuilderExtensions
    {
        public static QueryFramework.Abstractions.Builders.IQueryConditionBuilder WithOpenBracket(this QueryFramework.Abstractions.Builders.IQueryConditionBuilder instance, bool openBracket = true)
        {
            instance.OpenBracket = openBracket;
            return instance;
        }

        public static QueryFramework.Abstractions.Builders.IQueryConditionBuilder WithCloseBracket(this QueryFramework.Abstractions.Builders.IQueryConditionBuilder instance, bool closeBracket = true)
        {
            instance.CloseBracket = closeBracket;
            return instance;
        }

        public static QueryFramework.Abstractions.Builders.IQueryConditionBuilder WithField(this QueryFramework.Abstractions.Builders.IQueryConditionBuilder instance, QueryFramework.Abstractions.Builders.IQueryExpressionBuilder field)
        {
            instance.Field = field;
            return instance;
        }

        public static QueryFramework.Abstractions.Builders.IQueryConditionBuilder WithOperator(this QueryFramework.Abstractions.Builders.IQueryConditionBuilder instance, QueryFramework.Abstractions.QueryOperator @operator)
        {
            instance.Operator = @operator;
            return instance;
        }

        public static QueryFramework.Abstractions.Builders.IQueryConditionBuilder WithValue(this QueryFramework.Abstractions.Builders.IQueryConditionBuilder instance, object? value)
        {
            instance.Value = value;
            return instance;
        }

        public static QueryFramework.Abstractions.Builders.IQueryConditionBuilder WithCombination(this QueryFramework.Abstractions.Builders.IQueryConditionBuilder instance, QueryFramework.Abstractions.QueryCombination combination)
        {
            instance.Combination = combination;
            return instance;
        }

        public static QueryFramework.Abstractions.Builders.IQueryConditionBuilder WithField(this QueryFramework.Abstractions.Builders.IQueryConditionBuilder instance, string fieldName)
        {
            instance.Field.FieldName = fieldName;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class QueryExpressionBuilderExtensions
    {
        public static QueryFramework.Abstractions.Builders.IQueryExpressionBuilder WithFieldName(this QueryFramework.Abstractions.Builders.IQueryExpressionBuilder instance, string fieldName)
        {
            instance.FieldName = fieldName;
            return instance;
        }

        public static QueryFramework.Abstractions.Builders.IQueryExpressionBuilder WithFunction(this QueryFramework.Abstractions.Builders.IQueryExpressionBuilder instance, QueryFramework.Abstractions.Builders.IQueryExpressionFunctionBuilder? function)
        {
            instance.Function = function;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class QueryExpressionFunctionBuilderExtensions
    {
        public static QueryFramework.Abstractions.Builders.IQueryExpressionFunctionBuilder WithInnerFunction(this QueryFramework.Abstractions.Builders.IQueryExpressionFunctionBuilder instance, QueryFramework.Abstractions.Builders.IQueryExpressionFunctionBuilder? innerFunction)
        {
            instance.InnerFunction = innerFunction;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class QueryParameterBuilderExtensions
    {
        public static QueryFramework.Abstractions.Builders.IQueryParameterBuilder WithName(this QueryFramework.Abstractions.Builders.IQueryParameterBuilder instance, string name)
        {
            instance.Name = name;
            return instance;
        }

        public static QueryFramework.Abstractions.Builders.IQueryParameterBuilder WithValue(this QueryFramework.Abstractions.Builders.IQueryParameterBuilder instance, object value)
        {
            instance.Value = value;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class QueryParameterValueBuilderExtensions
    {
        public static QueryFramework.Abstractions.Builders.IQueryParameterValueBuilder WithName(this QueryFramework.Abstractions.Builders.IQueryParameterValueBuilder instance, string name)
        {
            instance.Name = name;
            return instance;
        }
    }
#nullable restore

#nullable enable
    public static partial class QuerySortOrderBuilderExtensions
    {
        public static QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder WithField(this QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder instance, QueryFramework.Abstractions.Builders.IQueryExpressionBuilder field)
        {
            instance.Field = field;
            return instance;
        }

        public static QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder WithOrder(this QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder instance, QueryFramework.Abstractions.QuerySortOrderDirection order)
        {
            instance.Order = order;
            return instance;
        }

        public static QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder WithField(this QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder instance, string fieldName)
        {
            instance.Field.FieldName = fieldName;
            return instance;
        }
    }
#nullable restore
}
