// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QueryFramework.Abstractions.Extensions
{
#nullable enable
    public static partial class QueryParameterValueBuilderExtensions
    {
        public static T WithName<T>(this T instance, string name)
            where T : QueryFramework.Abstractions.Builders.IQueryParameterValueBuilder
        {
            instance.Name = name;
            return instance;
        }
    }
#nullable restore
}

