// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.1
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using ModelFramework.Objects.Builders;
using ModelFramework.Objects.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QueryFramework.CodeGeneration.CodeGenerationProviders
{
#nullable enable
    public partial class QueryFrameworkCSharpClassBase
    {
        protected static ModelFramework.Objects.Contracts.ITypeBase[] GetModels()
        {
            return new[]
            {
                new ClassBuilder
                {
                    Namespace = @"QueryFramework.Abstractions",
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"OpenBracket",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"CloseBracket",
                            TypeName = @"System.Boolean",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Field",
                            TypeName = @"QueryFramework.Abstractions.IQueryExpression",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Operator",
                            TypeName = @"QueryFramework.Abstractions.QueryOperator",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Value",
                            TypeName = @"System.Object",
                            IsNullable = true,
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Combination",
                            TypeName = @"QueryFramework.Abstractions.QueryCombination",
                        },
                    } ),
                    Name = @"IQueryCondition",
                },
                new ClassBuilder
                {
                    Namespace = @"QueryFramework.Abstractions",
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"FieldName",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Function",
                            TypeName = @"QueryFramework.Abstractions.IQueryExpressionFunction",
                            IsNullable = true,
                        },
                    } ),
                    Name = @"IQueryExpression",
                },
                new ClassBuilder
                {
                    Namespace = @"QueryFramework.Abstractions",
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"InnerFunction",
                            TypeName = @"QueryFramework.Abstractions.IQueryExpressionFunction",
                            IsNullable = true,
                        },
                    } ),
                    Methods = new List<ClassMethodBuilder>(new[]
                    {
                        new ClassMethodBuilder
                        {
                            Virtual = true,
                            Abstract = true,
                            Name = @"ToBuilder",
                            TypeName = @"QueryFramework.Abstractions.Builders.IQueryExpressionFunctionBuilder",
                        },
                    } ),
                    Name = @"IQueryExpressionFunction",
                },
                new ClassBuilder
                {
                    Namespace = @"QueryFramework.Abstractions",
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Value",
                            TypeName = @"System.Object",
                        },
                    } ),
                    Name = @"IQueryParameter",
                },
                new ClassBuilder
                {
                    Namespace = @"QueryFramework.Abstractions",
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Name",
                            TypeName = @"System.String",
                        },
                    } ),
                    Name = @"IQueryParameterValue",
                },
                new ClassBuilder
                {
                    Namespace = @"QueryFramework.Abstractions",
                    Properties = new List<ClassPropertyBuilder>(new[]
                    {
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Field",
                            TypeName = @"QueryFramework.Abstractions.IQueryExpression",
                        },
                        new ClassPropertyBuilder
                        {
                            HasSetter = false,
                            Name = @"Order",
                            TypeName = @"QueryFramework.Abstractions.QuerySortOrderDirection",
                        },
                    } ),
                    Name = @"IQuerySortOrder",
                },
            }.Select(x => x.Build()).ToArray();
        }
    }
#nullable restore
}
