// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.6
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace QueryFramework.Core.Conditions
{
    public partial record ComposableCondition : QueryFramework.Core.Condition, QueryFramework.Abstractions.ICondition
    {
        public System.StringComparison StringComparison
        {
            get;
        }

        public QueryFramework.Abstractions.IExpression LeftExpression
        {
            get;
        }

        public QueryFramework.Abstractions.IOperator Operator
        {
            get;
        }

        public QueryFramework.Abstractions.IExpression RightExpression
        {
            get;
        }

        public System.Nullable<QueryFramework.Abstractions.Domains.Combination> Combination
        {
            get;
        }

        public bool StartGroup
        {
            get;
        }

        public bool EndGroup
        {
            get;
        }

        public ComposableCondition(System.StringComparison stringComparison, QueryFramework.Abstractions.IExpression leftExpression, QueryFramework.Abstractions.IOperator @operator, QueryFramework.Abstractions.IExpression rightExpression, System.Nullable<QueryFramework.Abstractions.Domains.Combination> combination, bool startGroup, bool endGroup) : base()
        {
            this.StringComparison = stringComparison;
            this.LeftExpression = leftExpression;
            this.Operator = @operator;
            this.RightExpression = rightExpression;
            this.Combination = combination;
            this.StartGroup = startGroup;
            this.EndGroup = endGroup;
            System.ComponentModel.DataAnnotations.Validator.ValidateObject(this, new System.ComponentModel.DataAnnotations.ValidationContext(this, null, null), true);
        }

        public override QueryFramework.Abstractions.Builders.IConditionBuilder ToBuilder()
        {
            return ToTypedBuilder();
        }

        public QueryFramework.Core.Builders.Conditions.ComposableConditionBuilder ToTypedBuilder()
        {
            return new QueryFramework.Core.Builders.Conditions.ComposableConditionBuilder(this);
        }

        QueryFramework.Abstractions.Builders.IConditionBuilder QueryFramework.Abstractions.ICondition.ToBuilder()
        {
            return ToTypedBuilder();
        }
    }
}
#nullable disable
