// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 9.0.6
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
#nullable enable
namespace QueryFramework.Abstractions
{
    public partial interface ICondition
    {
        System.StringComparison StringComparison
        {
            get;
        }

        CrossCutting.Utilities.ExpressionEvaluator.IEvaluatable LeftExpression
        {
            get;
        }

        QueryFramework.Abstractions.IOperator Operator
        {
            get;
        }

        CrossCutting.Utilities.ExpressionEvaluator.IEvaluatable RightExpression
        {
            get;
        }

        System.Nullable<QueryFramework.Abstractions.Domains.Combination> Combination
        {
            get;
        }

        bool StartGroup
        {
            get;
        }

        bool EndGroup
        {
            get;
        }

        QueryFramework.Abstractions.Builders.IConditionBuilder ToBuilder();
    }
    public partial interface IDataObjectNameQuery : QueryFramework.Abstractions.IQuery
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings = true)]
        string DataObjectName
        {
            get;
        }

        new QueryFramework.Abstractions.Builders.IDataObjectNameQueryBuilder ToBuilder();
    }
    public partial interface IFieldSelectionQuery : QueryFramework.Abstractions.IQuery
    {
        bool Distinct
        {
            get;
        }

        bool GetAllFields
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        System.Collections.Generic.IReadOnlyCollection<string> FieldNames
        {
            get;
        }

        new QueryFramework.Abstractions.Builders.IFieldSelectionQueryBuilder ToBuilder();
    }
    public partial interface IGroupingQuery : QueryFramework.Abstractions.IQuery
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        System.Collections.Generic.IReadOnlyCollection<CrossCutting.Utilities.ExpressionEvaluator.IExpression> GroupByFields
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        System.Collections.Generic.IReadOnlyCollection<QueryFramework.Abstractions.ICondition> GroupByFilter
        {
            get;
        }

        new QueryFramework.Abstractions.Builders.IGroupingQueryBuilder ToBuilder();
    }
    public partial interface IOperator
    {
        QueryFramework.Abstractions.Builders.IOperatorBuilder ToBuilder();
    }
    public partial interface IParameterizedQuery : QueryFramework.Abstractions.IQuery
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        System.Collections.Generic.IReadOnlyCollection<QueryFramework.Abstractions.IQueryParameter> Parameters
        {
            get;
        }

        new QueryFramework.Abstractions.Builders.IParameterizedQueryBuilder ToBuilder();
    }
    public partial interface IQuery
    {
        System.Nullable<int> Limit
        {
            get;
        }

        System.Nullable<int> Offset
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        [QueryFramework.CodeGeneration.ValidGroupsAttribute]
        System.Collections.Generic.IReadOnlyCollection<QueryFramework.Abstractions.ICondition> Filter
        {
            get;
        }

        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        System.Collections.Generic.IReadOnlyCollection<QueryFramework.Abstractions.IQuerySortOrder> OrderByFields
        {
            get;
        }

        QueryFramework.Abstractions.Builders.IQueryBuilder ToBuilder();
    }
    public partial interface IQueryParameter
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        string Name
        {
            get;
        }

        object? Value
        {
            get;
        }

        QueryFramework.Abstractions.Builders.IQueryParameterBuilder ToBuilder();
    }
    public partial interface IQueryParameterValue
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        string Name
        {
            get;
        }

        QueryFramework.Abstractions.Builders.IQueryParameterValueBuilder ToBuilder();
    }
    public partial interface IQuerySortOrder
    {
        [System.ComponentModel.DataAnnotations.RequiredAttribute]
        [CrossCutting.Common.DataAnnotations.ValidateObjectAttribute]
        CrossCutting.Utilities.ExpressionEvaluator.IExpression<string> FieldNameExpression
        {
            get;
        }

        QueryFramework.Abstractions.Domains.QuerySortOrderDirection Order
        {
            get;
        }

        QueryFramework.Abstractions.Builders.IQuerySortOrderBuilder ToBuilder();
    }
    public partial interface ISingleEntityQuery : QueryFramework.Abstractions.IQuery
    {
        new QueryFramework.Abstractions.Builders.ISingleEntityQueryBuilder ToBuilder();
    }
}
#nullable disable
