// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 6.0.2
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace QueryFramework.Abstractions
{
#nullable enable
    public partial interface IQueryCondition
    {
        bool OpenBracket
        {
            get;
        }

        bool CloseBracket
        {
            get;
        }

        QueryFramework.Abstractions.IQueryExpression Field
        {
            get;
        }

        QueryFramework.Abstractions.QueryOperator Operator
        {
            get;
        }

        object? Value
        {
            get;
        }

        QueryFramework.Abstractions.QueryCombination Combination
        {
            get;
        }
    }
#nullable restore

#nullable enable
    public partial interface IQueryExpression
    {
        string FieldName
        {
            get;
        }

        QueryFramework.Abstractions.IQueryExpressionFunction? Function
        {
            get;
        }
    }
#nullable restore

#nullable enable
    public partial interface IQueryExpressionFunction
    {
        QueryFramework.Abstractions.IQueryExpressionFunction? InnerFunction
        {
            get;
        }

        QueryFramework.Abstractions.Builders.IQueryExpressionFunctionBuilder ToBuilder();
    }
#nullable restore

#nullable enable
    public partial interface IQueryParameter
    {
        string Name
        {
            get;
        }

        object Value
        {
            get;
        }
    }
#nullable restore

#nullable enable
    public partial interface IQueryParameterValue
    {
        string Name
        {
            get;
        }
    }
#nullable restore

#nullable enable
    public partial interface IQuerySortOrder
    {
        QueryFramework.Abstractions.IQueryExpression Field
        {
            get;
        }

        QueryFramework.Abstractions.QuerySortOrderDirection Order
        {
            get;
        }
    }
#nullable restore
}
